# Development stage
FROM node:16-alpine AS development

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile --no-progress

# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm","run", "dev"]